{
	"dAppRequest_login_titleKnownDapp": "Login Request",
	"dAppRequest_login_subtitleKnownDapp": "**%s** is requesting that you login with a Persona.",
	"dAppRequest_login_titleNewDapp": "New Login Request",
	"dAppRequest_login_subtitleNewDapp": "**%s** is requesting that you login for the first time with a Persona.",
	"dAppRequest_login_choosePersona": "Choose a Persona",
	"dAppRequest_login_lastLoginWasOn": "Your last login was on %s",
	"dAppRequest_login_continue": "Continue",
	"dAppRequest_accountPermission_title": "Account Permission",
	"dAppRequest_accountPermission_numberOfAccountsAtLeast": "%d or more accounts",
	"dAppRequest_accountPermission_numberOfAccountsAtLeastZero": "Any number of accounts",
	"dAppRequest_accountPermission_numberOfAccountsExactly": "%d accounts",
	"dAppRequest_accountPermission_numberOfAccountsExactlyOne": "1 account",
	"dAppRequest_accountPermission_continue": "Continue",
	"dAppRequest_accountPermission_subtitle": "**%s** is requesting permission to *always* be able to view Account information when you login with this Persona.",
	"dAppRequest_accountPermission_updateInSettingsExplanation": "You can update this permission in wallet settings for this dApp at any time.",
	"dAppRequest_chooseAccounts_createNewAccount": "Create a New Account",
	"dAppRequest_chooseAccounts_successMessage": "You are now connected to %s. You can change your preferences for this dApp in wallet settings at any time.",
	"dAppRequest_chooseAccounts_successTitle": "dApp Connection Successful",
	"dAppRequest_chooseAccounts_verificationErrorTitle": "DApp error",
	"dAppRequest_chooseAccounts_continue": "Continue",
	"dAppRequest_chooseAccountsOneTime_title": "Account Request",
	"dAppRequest_chooseAccountsOneTime_subtitleAtLeast": "**%s** is making a one-time request for at least %d accounts.",
	"dAppRequest_chooseAccountsOneTime_subtitleAtLeastZero": "**%s** is making a one-time request for any number of accounts.",
	"dAppRequest_chooseAccountsOneTime_subtitleAtLeastOne": "**%s** is making a one-time request for at least 1 account.",
	"dAppRequest_chooseAccountsOneTime_subtitleExactly": "**%s** is making a one-time request for %d accounts.",
	"dAppRequest_chooseAccountsOneTime_subtitleExactlyOne": "**%s** is making a one-time request for 1 account.",
	"dAppRequest_chooseAccountsOngoing_title": "Account Permission",
	"dAppRequest_chooseAccountsOngoing_subtitleAtLeast": "Choose at least %d accounts you wish to use with **%s**.",
	"dAppRequest_chooseAccountsOngoing_subtitleAtLeastZero": "Choose any accounts you wish to use with **%s**.",
	"dAppRequest_chooseAccountsOngoing_subtitleAtLeastOne": "Choose at least 1 account you wish to use with **%s**.",
	"dAppRequest_chooseAccountsOngoing_subtitleExactly": "Choose %d accounts you wish to use with **%s**.",
	"dAppRequest_chooseAccountsOngoing_subtitleExactlyOne": "Choose 1 account you wish to use with **%s**.",
	"dAppRequest_personalDataOneTime_title": "One-Time Data Request",
	"dAppRequest_personalDataOneTime_chooseDataToProvide": "Choose the data to provide",
	"dAppRequest_personalDataOneTime_subtitle": "**%s** is requesting that you provide some pieces of personal data **just one time**",
	"dAppRequest_personalDataOneTime_continue": "Continue",
	"dAppRequest_personalDataPermission_title": "Personal Data Permission",
	"dAppRequest_personalDataPermission_subtitle": "**%s** is requesting permission to **always** be able to view the following personal data when you login with this Persona.",
	"dAppRequest_personalDataPermission_updateInSettingsExplanation": "You can update this permission in your Settings at any time.",
	"dAppRequest_personalDataPermission_continue": "Continue",
	"dAppRequest_validationOutcome_subtitleBadContent": "Invalid content",
	"dAppRequest_validationOutcome_subtitleIncompatibleVersion": "Incompatible connector extension",
	"dAppRequest_validationOutcome_subtitleWrongNetworkID": "Network mismatch",
	"dAppRequest_validationOutcome_devExplanationBadContent": "Invalid value of `numberOfAccountsInvalid`: must not be `exactly(0)` nor can `quantity` be negative",
	"dAppRequest_validationOutcome_devExplanationIncompatibleVersion": "%@ (CE: %@, wallet: %@)",
	"dAppRequest_validationOutcome_devExplanationInvalidOrigin": "'%@' is not valid origin.",
	"dAppRequest_validationOutcome_devExplanationInvalidDappDefinitionAddress": "'%@' is not valid account address.",
	"dAppRequest_validationOutcome_shortExplanationBadContent": "Invalid data in request",
	"dAppRequest_validationOutcome_shortExplanationIncompatibleVersionCEGreater": "Please update Radix Wallet",
	"dAppRequest_validationOutcome_shortExplanationIncompatibleVersionCENotGreater": "Please update Radix Connector browser extension",
	"dAppRequest_validationOutcome_shortExplanationInvalidOrigin": "Invalid origin",
	"dAppRequest_validationOutcome_shortExplanationInvalidDappDefinitionAddress": "Invalid dApp Definition Address",
	"dAppRequest_validationOutcome_shortExplanationP2PError": "Radix Connect connection error",
	"dAppRequest_validationOutcome_invalidRequestTitle": "Invalid Request.",
	"dAppRequest_validationOutcome_invalidRequestMessage": "Could not validate the dApp.",
	"dAppRequest_validationOutcome_invalidPersonaOrAccoubts": "dApp specified an invalid Persona or Account",
	"dAppRequest_validationOutcome_preAuthorizationExpirationTooClose": "Pre-authorization request was rejected because you weren't given enough time to review it.",
	"dAppRequest_validationOutcome_preAuthorizationExpired": "Pre-authorization request was rejected because it has already expired.",
	"dAppRequest_requestMalformedAlert_message": "Request received from dApp is invalid.",
	"dAppRequest_requestPersonaNotFoundAlert_message": "dApp specified an invalid Persona.",
	"dAppRequest_requestWrongNetworkAlert_message": "dApp made a request intended for network %@, but you are currently connected to %@.",
	"dAppRequest_responseFailureAlert_message": "Failed to send request response to dApp.",
	"dAppRequest_completion_title": "Success",
	"dAppRequest_completion_subtitle": "Request from %s complete",
	"dAppRequest_metadataLoadingAlert_message": "Danger! Bad dApp configuration, or you're being spoofed!",
	"dAppRequest_metadataLoadingPrompt": "Loadingâ€¦",
	"dAppRequest_metadata_unknownName": "Unknown dApp",
	"dAppRequest_metadata_wallet": "Radix Wallet",
	"dAppRequest_personalDataBox_edit": "Edit",
	"dAppRequest_personalDataBox_requiredInformation": "Required information:",
	"dAppRequest_personaProofOfOwnership_title": "Verify Persona Login",
	"dAppRequest_personaProofOfOwnership_subtitle": "**%s** is requesting verification of your login with the following Persona.",
	"dAppRequest_accountsProofOfOwnership_title": "Verify Account Ownership",
	"dAppRequest_accountsProofOfOwnership_subtitle": "**%s** is requesting verification that you own the following Account(s)."
}
